import 'package:equatable/equatable.dart';

enum DescriptorSource {
  /// Generated by an external AI / crawl pipeline.
  aiGenerated,

  /// Explicitly entered by the user.
  userDefined,

  /// Derived from aggregate user feedback.
  feedbackDerived,
}

/// A semantic descriptor attached to a [PlaceNode].
///
/// Lives in the public semantic layer. Descriptors are used for
/// soft-constraint matching against [PreferenceTag]s during the
/// recommendation pipeline.
///
/// Examples:
///   "noisy sports-bar atmosphere"
///   "intimate candle-lit setting"
///   "family-friendly with kids menu"
///   "trendy Instagram-worthy interior"
class SemanticDescriptor extends Equatable {
  final String id;
  final String placeNodeId;
  final String descriptor;
  final DescriptorSource source;

  /// Relevance / confidence weight (0.0 – 1.0).
  final double weight;

  /// Optional embedding vector stored as a JSON-serialised list.
  /// Used for fast cosine-similarity ranking.
  final String? embeddingJson;

  final DateTime createdAt;

  const SemanticDescriptor({
    required this.id,
    required this.placeNodeId,
    required this.descriptor,
    this.source = DescriptorSource.aiGenerated,
    this.weight = 1.0,
    this.embeddingJson,
    required this.createdAt,
  });

  SemanticDescriptor copyWith({
    String? id,
    String? placeNodeId,
    String? descriptor,
    DescriptorSource? source,
    double? weight,
    String? embeddingJson,
    DateTime? createdAt,
  }) {
    return SemanticDescriptor(
      id: id ?? this.id,
      placeNodeId: placeNodeId ?? this.placeNodeId,
      descriptor: descriptor ?? this.descriptor,
      source: source ?? this.source,
      weight: weight ?? this.weight,
      embeddingJson: embeddingJson ?? this.embeddingJson,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  List<Object?> get props =>
      [id, placeNodeId, descriptor, source, weight, embeddingJson, createdAt];
}
